runtime: python313

# entrypoint: gunicorn -b :$PORT main:app
entrypoint: gunicorn -k eventlet -w 1 -b :$PORT main:app

env_variables:
  GAE_ENV: flex

handlers:
  - url: /static
    static_dir: static/
  - url: /.*  # This routes everything to the backend
    script: auto
