runtime: python313
env: standard

# entrypoint: gunicorn -b :$PORT main:app
entrypoint: gunicorn -k eventlet -w 1 -b :$PORT main:app                                                                                                                                                                                                                           │
automatic_scaling:
  min_instances: 0
  max_instances: 7


# env_variables:
#   GAE_ENV: flex

handlers:
  - url: /static
    static_dir: static/
  - url: /.*  # This routes everything to the backend
    script: auto